# Generated by Django 4.0.4 on 2022-06-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlehistory',
            old_name='enemy_nickname',
            new_name='enemy_game_name',
        ),
        migrations.RenameField(
            model_name='battleunit',
            old_name='attack_max_range',
            new_name='max_attack_range',
        ),
        migrations.RenameField(
            model_name='battleunit',
            old_name='move_range',
            new_name='max_move_range',
        ),
        migrations.RenameField(
            model_name='battleunit',
            old_name='start_level',
            new_name='start_level_buy',
        ),
        migrations.RemoveField(
            model_name='battleunit',
            name='time_create',
        ),
    ]
