# Generated by Django 4.0.5 on 2022-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_rename_enemy_nickname_battlehistory_enemy_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deck_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='units_in_deck',
            field=models.IntegerField(default=0),
        ),
    ]
