# Generated by Django 4.0.5 on 2022-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100)),
                ('player_1_id', models.IntegerField(null=True)),
                ('player_2_id', models.IntegerField(null=True)),
                ('player_1_game_name', models.CharField(blank=True, max_length=100)),
                ('player_2_game_name', models.CharField(blank=True, max_length=100)),
                ('is_started', models.BooleanField(default=False)),
            ],
        ),
    ]
