# Generated by Django 4.0.5 on 2022-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlesession',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='battlesession',
            name='player_1_game_name',
        ),
        migrations.RemoveField(
            model_name='battlesession',
            name='player_1_id',
        ),
        migrations.RemoveField(
            model_name='battlesession',
            name='player_2_game_name',
        ),
        migrations.RemoveField(
            model_name='battlesession',
            name='player_2_id',
        ),
        migrations.AddField(
            model_name='battlesession',
            name='players_count',
            field=models.IntegerField(default=0),
        ),
    ]
