# Generated by Django 4.0.5 on 2022-07-08 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle_app', '0002_remove_battlesession_is_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesession',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battlesession',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
